POST http://localhost:5000/api/phones
Content-Type: application/json

{
  "model": "Galaxy S24",
  "brand": "Samsung",
  "productionYear": 2024,
  "ramSize": 8,
  "processor": "Exynos 2400",
  "screenDiagonal": 6.2,
  "hasNfc": true
}

###

GET http://localhost:5000/api/phones

###

GET http://localhost:5000/api/phones/1

###

GET http://localhost:5000/api/phones/111

###

DELETE http://localhost:5000/api/phones/21

###

DELETE http://localhost:5000/api/phones/111

###

PUT http://localhost:5000/api/phones/1
Content-Type: application/json

{
  "model": "iPhone 15",
  "brand": "Apple",
  "productionYear": 2023,
  "ramSize": 6,
  "processor": "A16 Bionic",
  "screenDiagonal": 6.1,
  "hasNfc": true
}

###

PUT http://localhost:5000/api/phones/1000
Content-Type: application/json

{
  "model": "Pixel 9",
  "brand": "Google",
  "productionYear": 2024,
  "ramSize": 12,
  "processor": "Tensor G4",
  "screenDiagonal": 6.3,
  "hasNfc": true
}

###

PUT http://localhost:5000/api/phones/2
Content-Type: application/json

{
  "model": "",
  "brand": "A",
  "productionYear": 1999,
  "ramSize": 0,
  "processor": "",
  "screenDiagonal": 0,
  "hasNfc": "yes"
}